### ISSUE TITLE
AxeView isObscured

### ISSUE THREAD

**Issue by cyono** [dequelabs/axe-android#102]
Enable a configuration that tells end-users when an AxeView is being partially or completely obscured by another view rendered "above" it in the hierarchy.

Develop a proof-of-concept with common design patterns:
- BottomNavBar
- Horizontal scroll RecyclerView
- Tab navigation

**Comment by devchan4188** [comment]
The POC for isObscured compares the views according the hierarchy the problem with this implementation is that if a view is overlapped by a view which is rendered before itself then it will not be marked as isObscured.

To overcome this problem if we consider all the views in hierarchy against each other then we do not have track which view is being considered against which because of which a view will be marked isObscured by its own parent.

There are two ways to simply resolve this but need further research:
- isVisibleToUser property of AllyNodeInfoCompat and create a allyNodeInfo from a view in Attest and get IsVisibleToUser from it.
- Another way is to get height of the view or measured height of the view (has to be researched) and compare it with the height from the Bounds in Screen height of the view.

**Comment by devchan4188** [comment]
This issue will be addressed in separate issues.
