### ISSUE TITLE
Rules documentation and details

### ISSUE THREAD

**Issue by renatoi** [dequelabs/axe-android#29]
Does axe-android have more documentation about each rule, why they exist, and how to fix them? I think this type of documentation would be extremely useful.

Sorry if this is already somewhere but I tried and couldn't find it.

**Comment by chriscm2006** [comment]
duplate of: #28 

Yes, we will be publishing documentation on our rules, collaboration details, etc. This will come out roughly the same time as the iOS library release. For tracking purposes. I consider this a duplicate of #28. That issue is a more complicated version of this, but to me, solves the same problem, which is a clear need for documentation and understanding of how to utilize the library and what it reports.
