### ISSUE TITLE
[BUG]: ColorContrast check is scanning too many pixels

### ISSUE THREAD

**Issue by DaveTryon** [dequelabs/axe-android#62]
When calling `AccessibilityNodeInfo.getBoundsInScreen`, the returned `boundsInScreen` values appear to be _inclusive_ on the top and left values, but _exclusive_ on the bottom and right values. I was unable to find this in the Android documents, but it's entirely consistent with how Windows and other GUI's report bounding rectangles. Here are 2 simple `boundsInScreen` cases to demonstrate this:

1. Scan any app and look at the `boundsInScreen` value reported for the top-level `AxeView`. On a device with a 1080 x 1920 display, the reported bounds are:
```
      "boundsInScreen": {
        "bottom": 1920,
        "left": 0,
        "right": 1080,
        "top": 0
      }
```
The valid pixels in this display range from 0 ,0 in the upper left to 1079, 1919 in the bottom right. The X index of 1080 is off the right edge of the screen, and the Y value of 1920 is off the bottom edge.

2. If you scan an app with adjacent controls (I used the Bing search app, which puts some adjacent buttons in the bottom right corner), then look at the reported bounds, you'll see `boundsInScreen` values with identical top and bottom values, but the `right` value for one is the same as the `left` value for the next (non-bounds values omitted for clarity):

        {
          "axeViewId": "1524989317",
          "boundsInScreen": {
            "bottom": 1773,
            "left": 595,
            "right": 711,
            "top": 1660
          },
        },
        {
          "axeViewId": "2098106477",
          "boundsInScreen": {
            "bottom": 1773,
            "left": 711,
            "right": 827,
            "top": 1660
          },
        },
        {
          "axeViewId": "-1850718490",
          "boundsInScreen": {
            "bottom": 1773,
            "left": 827,
            "right": 943,
            "top": 1660
          },
        },

When `AxeImage.runColorContastCalculation` evaluates these views, it scans the inclusive ranges of 595 to 711, then 711 to 827, then 827 to 943. The values of 711 and 827 are scanned twice, when they should each belong only to a single view. The dual scanning is easy to confirm by looking at the x and y values passed to `AxeImage.pixel`

This is easy to fix, but the question is the scope of the fix. It could be scoped to just `AxeImage.runColorContrastCalculation` (run the test on a slightly smaller frame), or it could be handled at the `AxeRect` scope (modify both `isWithin` and `isTrailingEdge`)--the latter scope may be technically more correct, but it would have potentially unexpected side effects.

**Comment by chriscm2006** [comment]
I don't believe this will cause any negative behaviors, except for maybe O(W) extra computation cycles now and then where W = width of the image.

Very rarely should an image end up being looked at in its entirety. In fact, one scan through the center of the image is all that most images will take. In fact, it will never look at these particular pixels. It should end WELL before this. There is a function in AxeRect that says:

`binaryRowSwarch(final int maxWidthBetweenRows)`

Roughly what this function does is... say you have a 20 pixel high image. And we called `binaryRowSearch(5)` The iterator returned by binaryRosearch will scan an image like this.

- Row 10: Scan all pixels in row.
- Row 15: Scan all pixels in row.
- Row 17: Skipped. (17 - 15) > 5
- Row 12: Skipped (15 - 12) > 5
- Row 5: Scan all pixels in row.
- Row 7: Skip...
- Row 2: Skip

Under most scenarios in which we have a normal text box, the algorithm should be done after scanning row 10. But under no scenario would we ever expect to look at the top or bottom of the rectangle and we certainly wouldn't expect that having the precise bounds of the box to impact performance (1 extra row when `X % maxWidthBetweenRows == 0`) and certainly not accuracy.

If you can find a test case that shows otherwise please let me know!

**Comment by DaveTryon** [comment]
@chriscm2006, I agree that there will probably never be a case where we exceed the bottom border, but what about the right border? In most cases, there will be a pixel to the right of the view, but what happens if the view fills the entire horizontal space? If the display is 1200 pixels wide, we'll try to grab pixel 1201, which could have unpredictable behavior.
